INSERT INTO tb_game_list (name) VALUES ('Aventura e RPG');
INSERT INTO tb_game_list (name) VALUES ('Jogos de plataforma');



INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Mass Effect Trilogy', 4.8, 2012, 'Role-playing (RPG), Shooter', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java spring-dslist/main/resources/1.png', 'Saga épica de RPG de ficção científica com narrativa guiada por escolhas.', 'A Trilogia Mass Effect acompanha a jornada épica do Comandante Shepard em um universo de ficção científica ricamente detalhado. Os jogadores moldam a história por meio de escolhas cruciais, forjando alianças, enfrentando a ameaça dos Reapers e explorando planetas diversos. Com mecânicas profundas de RPG, combate intenso em terceira pessoa e uma narrativa expansiva, a trilogia combina uma história emocional com ação eletrizante, oferecendo uma experiência altamente rejogável em três jogos aclamados pela crítica.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Red Dead Redemption 2', 4.7, 2018, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java spring-dslist/main/resources/2.png', 'Obra-prima de mundo aberto no Velho Oeste com narrativa imersiva.', 'Red Dead Redemption 2 é uma obra-prima de mundo aberto ambientada nos últimos dias do Velho Oeste. Siga Arthur Morgan e a gangue Van der Linde enquanto navegam por uma história envolvente de lealdade, traição e sobrevivência. Com paisagens de tirar o fôlego, narrativa imersiva e atenção incomparável aos detalhes, o jogo oferece missões dinâmicas, interações profundas com personagens e um mundo vivo onde cada escolha molda a jornada.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('The Witcher 3: Wild Hunt', 4.7, 2014, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java spring-dslist/main/resources/3.png', 'RPG de fantasia vasto com missões profundas e escolhas morais.', 'The Witcher 3: Wild Hunt segue Geralt de Rívia, um caçador de monstros habilidoso, em um mundo aberto devastado pela guerra. Com missões intricadas, personagens ricos e uma narrativa moralmente complexa, os jogadores exploram um reino de fantasia visualmente deslumbrante, repleto de criaturas mortais e escolhas difíceis. Os sistemas profundos de RPG, combate envolvente e expansões robustas tornam o jogo um marco em narrativa e exploração.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sekiro: Shadows Die Twice', 3.8, 2019, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java spring-dslist/main/resources/4.png', 'Aventura desafiadora com furtividade e combate preciso.', 'Sekiro: Shadows Die Twice é uma aventura de ação brutal ambientada no Japão feudal. Os jogadores controlam o Lobo, um shinobi em busca de vingança, em um mundo de furtividade, combate preciso e elementos sobrenaturais. Com jogabilidade desafiadora, design de níveis intricado e uma história envolvente, o jogo exige domínio de suas mecânicas únicas, recompensando habilidade e perseverança com uma experiência profundamente satisfatória.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ghost of Tsushima', 4.6, 2012, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java spring-dslist/main/resources/5.png', 'Aventura samurai de mundo aberto com visuais e combates incríveis.', 'Ghost of Tsushima mergulha os jogadores no Japão do século XIII como Jin Sakai, um samurai lutando para repelir uma invasão mongol. Esta aventura de ação de mundo aberto combina furtividade, combate intenso e visuais de tirar o fôlego. Com uma história emocionante de honra e sacrifício, exploração dinâmica e duelos cinematográficos, o jogo oferece uma jornada inesquecível em um cenário histórico belamente construído.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Super Mario World', 4.7, 1990, 'Platform', 'Super Ness, PC', 'https://raw.githubusercontent.com/devsuperior/java spring-dslist/main/resources/6.png', 'Plataformer clássico com níveis coloridos e power-ups icônicos.', 'Super Mario World é um platformer atemporal estrelado por Mario na vibrante Terra dos Dinossauros. Com power-ups icônicos, controles precisos e design de níveis criativo, os jogadores navegam por mundos coloridos cheios de segredos e inimigos. Este clássico do SNES apresentou Yoshi, combinando charme, desafio e rejogabilidade para criar um título fundamental no gênero de plataforma.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Hollow Knight', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java spring-dslist/main/resources/7.png', 'Metroidvania atmosférico com combate e exploração desafiadores.', 'Hollow Knight é um Metroidvania belamente assombroso ambientado no reino subterrâneo de Hallownest. Os jogadores controlam um cavaleiro silencioso explorando ambientes desenhados à mão, repletos de inimigos desafiadores e uma rica mitologia. Com plataforma precisa, combate recompensador e uma atmosfera melancólica, o jogo oferece um mundo vasto e interconectado que cativa com seus segredos e profundidade emocional.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ori and the Blind Forest', 4, 2015, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java spring-dslist/main/resources/8.png', 'Plataformer emocional com arte deslumbrante e jogabilidade fluida.', 'Ori and the Blind Forest é um platformer visualmente deslumbrante que segue Ori, um espírito guardião, em uma jornada emocional para restaurar uma floresta moribunda. Com movimentos fluidos, quebra-cabeças desafiadores e uma história comovente, o jogo combina exploração no estilo Metroidvania com arte e música de tirar o fôlego, criando uma experiência profundamente tocante e memorável.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Cuphead', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java spring-dslist/main/resources/9.png', 'Plataformer retrô com batalhas de chefes difíceis e arte única.', 'Cuphead é um platformer run-and-gun inspirado em desenhos animados dos anos 1930, conhecido por sua dificuldade implacável e estilo artístico marcante. Os jogadores controlam Cuphead e Mugman, enfrentando chefes excêntricos em uma série de níveis rápidos com trilha sonora de jazz. Com controles precisos, visuais únicos e desafios intensos, é um título destacado que testa habilidade e perseverança.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sonic CD', 4, 1993, 'Platform', 'Sega CD, PC', 'https://raw.githubusercontent.com/devsuperior/java spring-dslist/main/resources/10.png', 'Plataformer veloz com viagem no tempo e níveis vibrantes.', 'Sonic CD é um platformer clássico estrelado por Sonic the Hedgehog, correndo por níveis distorcidos pelo tempo para salvar o Pequeno Planeta. Com mecânicas inovadoras de viagem no tempo, visuais vibrantes e uma trilha sonora memorável, os jogadores atravessam estágios únicos cheios de velocidade e segredos. Esta joia do Sega CD permanece como uma entrada amada na série Sonic.');

INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 3, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 4, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 5, 4);

INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 6, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 7, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 8, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 9, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 10, 4);